on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

name: render-readme

jobs:
  render-readme:
    if: "contains(github.event.head_commit.message, 'render rmd')"
    runs-on: macOS-latest
    timeout-minutes: 20
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install Dependencies
        run: |
          install.packages(c('remotes', 'rmarkdown')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Render readme
        run: |
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}

      - name: Commit README.md
        run: |
          git add README.md
          git commit -m 'Re-build README.Rmd' || echo "Render README"
          git push origin || echo "Render README"

      - name: action-slack
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3.0.0
        with:
          status: ${{ job.status }}
          author_name: "github action: ${{github.workflow}}"
          fields: repo, ref, commit, author, message
